### ISSUE TITLE
cpuburn-a9 broken?

### ISSUE THREAD

**Issue by NastyRigger** [ssvb/cpuburn-arm#6]
All other versions run fine on my linux system (neon and vfp4 supported), only cpuburn-a9 SIGILLs:

```asm
Starting program: /home/guest/cpuburn-arm/cpuburn-a9 

Program received signal SIGILL, Illegal instruction.
0x000083b8 in sysconf@plt ()
(gdb) bt
#0  0x000083b8 in sysconf@plt ()
#1  0x000084b8 in main () at cpuburn-a9.S:57
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) disass
Dump of assembler code for function sysconf@plt:
=> 0x000083b8 <+0>:     add     r12, pc, #0, 12
   0x000083bc <+4>:     add     r12, r12, #8192 ; 0x2000
   0x000083c0 <+8>:     ldr     pc, [r12, #3172]!       ; 0xc64
````

**Comment by ssvb** [comment]
Apparently it segfaults when trying to call the sysconf function. My only guess is that something might be wrong with the arm/thumb state switching. Can you try to replace 'blx' instructions with 'bl' and check if this helps?

If you can provide some additional information about your CPU, Linux distribution and toolchain, that would help too.

**Comment by NastyRigger** [comment]
After a reboot/recompile I can't reproduce the crash any more. The system must have become unstable and generated bad instructions or sth. Sorry for the fuss!
